/*
 * StarshipOS Copyright (c) 2021-2025. R.A. James
 */

/*
 * @test
 * @bug 8273408
 * @summary The compiler shouldn't crash when record component uses the class generated by the annotation processor.
 * @library /tools/lib
 * @modules jdk.compiler/com.sun.tools.javac.api
 *          jdk.compiler/com.sun.tools.javac.main
 * @compile GenerateTypeProcessor.java
 * @run main RecordComponentTypeTest
 */

import java.lang.classfile.*;
import java.lang.classfile.attribute.RuntimeVisibleAnnotationsAttribute;

import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;

import toolbox.JavacTask;
import toolbox.TestRunner;
import toolbox.ToolBox;
import toolbox.Task;

public class RecordComponentTypeTest extends TestRunner {

    ToolBox tb;
    ClassModel cf;

    public RecordComponentTypeTest() {
        super(System.err);
        tb = new ToolBox();
    }

    public static void main(String[] args) throws Exception {
        RecordComponentTypeTest t = new RecordComponentTypeTest();
        t.runTests();
    }

    @Test
    public void testRecordComponentUsingGeneratedType() throws Exception {
        String code = "public record RecordComponentUsingGeneratedType(GeneratedType generatedType) { }";
        Path curPath = Path.of(".");

        // Have no annotation processor.
        List<String> output = new JavacTask(tb)
                .sources(code)
                .outdir(curPath)
                .options("-XDrawDiagnostics")
                .run(Task.Expect.FAIL)
                .writeAll()
                .getOutputLines(Task.OutputKind.DIRECT);
        List<String> expected = Arrays.asList(
                "RecordComponentUsingGeneratedType.java:1:49: compiler.err.cant.resolve.location: kindname.class, " +
                "GeneratedType, , , (compiler.misc.location: kindname.class, RecordComponentUsingGeneratedType, null)",
                "1 error");
        tb.checkEqual(expected, output);

        // Have annotation processor, and processor generates expected type.
        new JavacTask(tb)
                .sources(code)
                .options("-processor", "GenerateTypeProcessor")
                .outdir(curPath)
                .run();
    }

    @Test
    public void testRecordComponentUsingUnknownType() throws Exception {
        String code = "public record RecordComponentUsingUnknownType(UnknownType unknownType) { }";
        Path curPath = Path.of(".");

        // Have no annotation processor.
        List<String> output = new JavacTask(tb)
                .sources(code)
                .outdir(curPath)
                .options("-XDrawDiagnostics")
                .run(Task.Expect.FAIL)
                .writeAll()
                .getOutputLines(Task.OutputKind.DIRECT);
        List<String> expected = Arrays.asList(
                "RecordComponentUsingUnknownType.java:1:47: compiler.err.cant.resolve.location: kindname.class, " +
                "UnknownType, , , (compiler.misc.location: kindname.class, RecordComponentUsingUnknownType, null)",
                "1 error");
        tb.checkEqual(expected, output);

        // Have annotation processor, but processor doesn't generate the expected type.
        List<String> output2 = new JavacTask(tb)
                .sources(code)
                .outdir(curPath)
                .options("-XDrawDiagnostics", "-processor", "GenerateTypeProcessor")
                .run(Task.Expect.FAIL)
                .writeAll()
                .getOutputLines(Task.OutputKind.DIRECT);
        List<String> expected2 = Arrays.asList(
                "RecordComponentUsingUnknownType.java:1:47: compiler.err.cant.resolve.location: kindname.class, " +
                "UnknownType, , , (compiler.misc.location: kindname.class, RecordComponentUsingUnknownType, null)",
                "1 error");
        tb.checkEqual(expected2, output2);
    }


    @Test
    public void testRecordComponentUsingGeneratedTypeWithAnnotation() throws Exception {
        String code = """
                import java.lang.annotation.Retention;
                import java.lang.annotation.RetentionPolicy;
                public record RecordComponentUsingGeneratedTypeWithAnnotation(@TestAnnotation GeneratedType generatedType) { }

                @Retention(RetentionPolicy.RUNTIME)
                @interface TestAnnotation { }
                """;
        Path curPath = Path.of(".");
        new JavacTask(tb)
                .sources(code)
                .options("-processor", "GenerateTypeProcessor")
                .outdir(curPath)
                .run();
        cf = ClassFile.of().parse(curPath.resolve("RecordComponentUsingGeneratedTypeWithAnnotation.class"));

        for (FieldModel field : cf.fields()) {
            if (field.fieldName().equalsString("generatedType")){
                checkRuntimeVisibleAnnotation(field);
            }
        }

        for (MethodModel method : cf.methods()) {
            if (method.methodName().equalsString("generatedType")) {
                checkRuntimeVisibleAnnotation(method);
            }
        }
    }

    private void checkRuntimeVisibleAnnotation(AttributedElement attributedElement) throws Exception {
        RuntimeVisibleAnnotationsAttribute annotations = attributedElement.findAttribute(Attributes.runtimeVisibleAnnotations()).orElseThrow();
        boolean hasAnnotation = false;
        for (Annotation annotation : annotations.annotations()) {
            if (annotation.classSymbol().descriptorString().equals("LTestAnnotation;")) {
                hasAnnotation = true;
            }
        }
        if (!hasAnnotation) {
            throw new AssertionError("Expected RuntimeVisibleAnnotation doesn't appear");
        }
    }
}
