/*
 * StarshipOS Copyright (c) 2020-2025. R.A. James
 */

package jdk.test.lib.format;

/**
 * A collection of formatting utilities
 */
public class Format {

    /**
     * Formats character as literal, using C-style escaping for unprintable symbols
     *
     * @param c character to format
     * @return formatted string representation of the character
     */
    public static String asLiteral(char c) {
        StringBuilder sb = new StringBuilder();
        appendCharToSb(c, sb);
        return sb.toString();
    }

    /**
     * Escapes String in C-style
     *
     * @param src source string
     * @return C-style escaped source string
     */
    public static String escapeString(String src) {
        StringBuilder sb = new StringBuilder();
        src.chars().forEachOrdered(
                (c) -> appendCharToSb((char) c, sb));
        return sb.toString();
    }

    /**
     * Formats Object as literal, using its String representation C-style escaped.
     *
     * @param o object to format
     * @return C-style escaped String representation of the object
     */
    public static String asLiteral(Object o) {
        if (o instanceof String) {
            return '"' + escapeString((String)o) + '"';
        } else if (o instanceof Character) {
            return asLiteral((char) o);
        } else if (o instanceof Byte) {
            return String.valueOf(o);
        } else {
            return escapeString(String.valueOf(o));
        }
    }

    /**
     * Formats a difference between two arrays with index of the first mismatch element,
     * and slices of arrays necessary to understand the problem, along with a failure mark.
     *
     * @param first first array to compare
     * @param second second array to compare
     * @return the difference, generated by the {@link ArrayDiff ArrayDiff}
     */
    public static String arrayDiff(Object first, Object second) {
        return ArrayDiff.of(first, second).format();
    }

    /**
     * Formats a difference between two arrays with index of the first mismatch element,
     * and slices of arrays necessary to understand the problem, along with a failure mark.
     * Takes into account maximum allowed width and context (in elements) before the mismatch.
     *
     * @param first first array to compare
     * @param second second array to compare
     * @param width the maximum allowed width in characters for the formatting
     * @param contextBefore maximum number of elements to print before those that differ
     * @return the difference, generated by the {@link ArrayDiff ArrayDiff}
     */
    public static String arrayDiff(Object first, Object second, int width, int contextBefore) {
        return ArrayDiff.of(first, second, width, contextBefore).format();
    }


    /**
     * Returns a string of spaces with length specified.
     *
     * @param width number of spaces in the resulting string
     * @return Padding string of spaces
     */
    public static String paddingForWidth(int width) {
        return " ".repeat(width);
    }

    private static void appendCharToSb(char c, StringBuilder sb) {
        if (c == 10) {
            sb.append("\\n");
        } else if (c == 13) {
            sb.append("\\r");
        } else if (c == 92) {
            sb.append("\\\\");
        } else if (c == 34) {
            sb.append("\\\"");
        } else if (c < 32 || c > 126) {
            sb.append("\\u" + String.format("%04X", (int) c));
        } else {
            sb.append(c);
        }
    }
}
