/*
 * StarshipOS Copyright (c) 2025. R.A. James
 */

public class TestCast6979683_BAD36 {
    //...
    //...
    static int iconvBAD2(Comparable<Integer> o) { return o; } //BAD: cast needed
    //...
    //...
    //...
}
