/*
 * StarshipOS Copyright (c) 2025. R.A. James
 */

public class TestCast6979683_BAD38 {
    //...
    //...
    //...
    //...
    static float cconvBAD1(Comparable<Character> o) { return o; } //BAD
    //...
}
