/*
 * StarshipOS Copyright (c) 2020-2025. R.A. James
 */

package transform;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;
import org.testng.annotations.Test;

/*
 * @test
 * @bug 8248348
 * @library /javax/xml/jaxp/libs /javax/xml/jaxp/unittest
 * @run testng transform.BCELHashCodeTest
 * @summary The addition of the hashCode() method to Instruction.java in BCEL 6.0
 * caused a regression. This test verifies that the issue has been fixed.
 */
public class BCELHashCodeTest {
    /**
     * Verifies the patch by attempting to create a transformer from the stylesheet.
     * The stylesheet contains an extra table-row with element-id="17921" that
     * causes the generated bytecode to exceed the 64Kbyte method size limit.
     * Splitting it into multiple methods requires mutating the instructions that
     * results in an Exception without the fix. The stylesheet would pass with
     * or without the fix if the extra table-row is removed.
     *
     * @throws TransformerConfigurationException if the test fails
     */
    @Test
    public void test() throws TransformerConfigurationException {
         StreamSource stylesheet = new StreamSource(this.getClass()
                 .getResourceAsStream("BCELHashCodeTest.xsl"));
         TransformerFactory tFactory =TransformerFactory.newInstance();
         Transformer transformer = tFactory.newTransformer(stylesheet);
    }
}
