/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_starship_CLibJNI */

#ifndef _Included_org_starship_CLibJNI
#define _Included_org_starship_CLibJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_starship_CLibJNI
 * Method:    sethostname
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_sethostname
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_starship_CLibJNI
 * Method:    gethostname
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_gethostname
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_starship_CLibJNI
 * Method:    mount
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_mount
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong, jstring);

/*
 * Class:     org_starship_CLibJNI
 * Method:    umount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_umount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_starship_CLibJNI
 * Method:    umount2
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_umount2
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_starship_CLibJNI
 * Method:    mknod
 * Signature: (Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_mknod
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     org_starship_CLibJNI
 * Method:    reboot
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_reboot
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_starship_CLibJNI
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_starship_CLibJNI_sync
  (JNIEnv *, jobject);

/*
 * Class:     org_starship_CLibJNI
 * Method:    execve
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_execve
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

/*
 * Class:     org_starship_CLibJNI
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_starship_CLibJNI_getenv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_starship_CLibJNI
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_starship_CLibJNI_setenv
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
