/*
 * StarshipOS Copyright (c) 2016-2025. R.A. James
 */

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.HexFormat;
import java.util.stream.Collectors;

/**
 * HexDumpReader provides utility methods to read a hex dump text file
 * and convert to an InputStream.  The format supported by the methods
 * can be generated by the following command.
 *
 * $ od -vw -t x1 foo | sed -r -e 's/^[0-9]+ ?//' -e 's/ //g' -e '/^$/d'
 */
public final class HexDumpReader {

    // Utility class should not be instantiated
    private HexDumpReader() {}

    /*
     * Converts a Hex dump file given by the String name into an InputStream
     * containing bytes. The expected format of the file should be given as lines
     * that are either:
     *  - Valid hexadecimal value(s) (two hexadecimal characters) combined with no
     *    spaces between. E.g. "ace95365" represents four hexadecimal values.
     *    There should not be an odd amount of hexadecimal characters. E.g. "ace"
     *  - Contain leading comments given by '#' (which are ignored). E.g. "#foo"
     *    Non-leading comments are not allowed. E.g. "ace953 #foo"
     *  - Empty (which are ignored).
     */
    public static InputStream getStreamFromHexDump(String fileName) throws IOException {
        return getStreamFromHexDump(new File(System.getProperty("test.src", "."),
                fileName));
    }

    // Overloaded version of getStreamFromHexDump() that takes the File itself as input.
    public static InputStream getStreamFromHexDump(File hexFile) throws IOException {
        // This hexString should only consist of valid hexadecimal digits and be even
        // otherwise an exception will be thrown when converting to bytes
        String hexString = Files.readAllLines(hexFile.toPath(), StandardCharsets.UTF_8)
                .stream()
                .map(String::trim)
                .filter(s -> !s.isEmpty() && !s.startsWith("#"))
                .collect(Collectors.joining());
        // Iterate the hex string and convert it to bytes
        byte[] bArray = HexFormat.of().parseHex(hexString);
        return new ByteArrayInputStream(bArray);
    }
}
