/*
 * StarshipOS Copyright (c) 2002-2025. R.A. James
 */

/*
 * @test
 * @bug 4720849
 * @summary  Standard doclet contains hard-coded version number
 * @library ../../lib
 * @modules jdk.javadoc/jdk.javadoc.internal.tool
 * @build javadoc.tester.*
 * @run main VersionNumber
 */


/**
 * Runs javadoc and runs regression tests on the resulting HTML.
 */
import javadoc.tester.JavadocTester;

public class VersionNumber extends JavadocTester {

    public static void main(String... args) throws Exception {
        var tester = new VersionNumber();
        tester.runTests();
    }

    @Test
    public void test() {
        javadoc("-d", "out",
                "p1");
        checkExit(Exit.OK);

        // Test the proper DOCTYPE element is present:
        checkOutput("p1/C.html", true,
                "<!-- Generated by javadoc (");
    }

}
