/*
 * StarshipOS Copyright (c) 2007-2025. R.A. James
 */
package nsk.jdi.ReferenceType.defaultStratum.defaultStratum004;

//    THIS TEST IS LINE NUMBER SENSITIVE

// Class contains method with several locations, do not edit this file because of line numbers are hardcoded in tests
public class TestClass2
{
    public TestClass2()
    {
        super();    // testStratumData::doTest()::testStratumData->at(0)
        int i = 0;  // testStratumData::doTest()::testStratumData->at(1)
        i++;        // testStratumData::doTest()::testStratumData->at(2)
        i++;        // testStratumData::doTest()::testStratumData->at(3)
        i++;        // testStratumData::doTest()::testStratumData->at(4)
        i++;        // testStratumData::doTest()::testStratumData->at(5)
        i++;        // testStratumData::doTest()::testStratumData->at(6)
    }               // testStratumData::doTest()::testStratumData->at(7)
}
