/*
 * StarshipOS Copyright (c) 2007-2025. R.A. James
 */
package nsk.jdi.ReferenceType.defaultStratum.defaultStratum004;

//    THIS TEST IS LINE NUMBER SENSITIVE

// Class contains method with several locations, do not edit this file because of line numbers are hardcoded in tests
public class TestClass3
{
    public TestClass3()
    {
        super();    // testStratumData::doTest()::testStratumData->at(0)
        int i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
    }               // testStratumData::doTest()::testStratumData->at(1)
}
