/*
 * StarshipOS Copyright (c) 1998-2025. R.A. James
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class EchoImpl_Stub
    extends java.rmi.server.RemoteStub
    implements Echo, java.rmi.Remote
{
    private static final long serialVersionUID = 2;

    private static java.lang.reflect.Method $method_echoNot_0;

    static {
        try {
            $method_echoNot_0 = Echo.class.getMethod("echoNot", new java.lang.Class[] {byte[].class});
        } catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError(
                "stub class initialization failed");
        }
    }

    // constructors
    public EchoImpl_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }

    // methods from remote interfaces

    // implementation of echoNot(byte[])
    public byte[] echoNot(byte[] $param_arrayOf_byte_1)
        throws java.rmi.RemoteException
    {
        try {
            Object $result = ref.invoke(this, $method_echoNot_0, new java.lang.Object[] {$param_arrayOf_byte_1}, -4295721514897591756L);
            return ((byte[]) $result);
        } catch (java.lang.RuntimeException e) {
            throw e;
        } catch (java.rmi.RemoteException e) {
            throw e;
        } catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}
