/*
 * StarshipOS Copyright (c) 2018-2025. R.A. James
 */

/*
 * @test
 * @bug 8203792 8243113
 * @summary Remove "compatibility" features from Head.java
 * @library /tools/lib ../../lib
 * @modules jdk.javadoc/jdk.javadoc.internal.tool
 * @build javadoc.tester.* toolbox.ToolBox builder.ClassBuilder
 * @run main TestHeadTag
 */


import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;

import builder.ClassBuilder;
import toolbox.ToolBox;

import javadoc.tester.JavadocTester;

public class TestHeadTag extends JavadocTester {

    final ToolBox tb;
    final String version = System.getProperty("java.specification.version");

    public static void main(String... args) throws Exception {
        var tester = new TestHeadTag();
        tester.runTests();
    }

    TestHeadTag() {
        tb = new ToolBox();
    }

    @Test
    public void test(Path base) throws Exception {
        Path srcDir = base.resolve("src");
        createTestClass(srcDir);

        Path outDir = base.resolve("out");
        javadoc("-d", outDir.toString(),
                "-sourcepath", srcDir.toString(),
                "pkg");

        checkExit(Exit.OK);

        checkOrder("pkg/A.html",
                "Generated by javadoc (" + version + ")",
                "<meta name=\"dc.created\"");
    }

    @Test
    public void testWithNoTimestamp(Path base) throws Exception {
        Path srcDir = base.resolve("src");
        createTestClass(srcDir);

        Path outDir = base.resolve("out-1");
        javadoc("-d", outDir.toString(),
                "-notimestamp",
                "-sourcepath", srcDir.toString(),
                "pkg");

        checkExit(Exit.OK);

        checkOutput("pkg/A.html", true,
                "<!-- Generated by javadoc (" + version + ") -->");
        checkOutput("pkg/A.html", false,
                "<meta name=\"dc.created\"");
    }

    void createTestClass(Path srcDir) throws Exception {
        new ClassBuilder(tb, "pkg.A")
                .setModifiers("public", "class")
                .write(srcDir);
    }
}
