/*
 * StarshipOS Copyright (c) 2007-2025. R.A. James
 */

//    THIS TEST IS LINE NUMBER SENSITIVE

package nsk.share.jdi.sde;

// Class contains 3 methods with several locations, do not edit this file because of line numbers are hardcoded in tests
public class TestClass1 {
    public TestClass1()
    {
        super(); // SDEDebugger.INIT_LINE
        int i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

    public void sde_testMethod1()
    {
        int i = 0; // SDEDebugger.METHOD1_LINE
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

    public void sde_testMethod2()
    {
        int i = 0; // SDEDebugger.METHOD2_LINE
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}
