/*
 * StarshipOS Copyright (c) 2010-2025. R.A. James
 */

/**
 * Class to exercise dependencies on the two source files generated by
 * T6634138.java, foo.WrittenAfterProcessing.java and
 * foo.package-info.java.
 */
public class ExerciseDependency {
    public static void main(String... args) {
        foo.WrittenAfterProcessing wap = new foo.WrittenAfterProcessing();
        java.lang.Package pkg = wap.getClass().getPackage();
        Deprecated d = pkg.getAnnotation(Deprecated.class);
        if (d == null)
            throw new RuntimeException();
    }
}
