/*
 * StarshipOS Copyright (c) 2013-2025. R.A. James
 */

/*
 * @test
 * @bug 8006346
 * @summary doclint should make allowance for headings generated by standard doclet
 * @compile -Xdoclint:all/public ImplicitHeadingsTest.java
 */

/**
 * <h2> Class heading </h2>
 */
public class ImplicitHeadingsTest {
    /**
     * <h4>Method heading</h4>
     */
    public void m() { }
}

