#
# StarshipOS Copyright (c) 2016-2025. R.A. James
#

CAP_TypeParameters=Type Parameters:
CAP_Parameters=Parameters:
CAP_Returns=Returns:
CAP_Thrown_Exceptions=Thrown Exceptions:
Inline_Returns=Returns {0}.
