/*
 * StarshipOS Copyright (c) 2005-2025. R.A. James
 */

// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class UnderscoreHost_Stub
    extends java.rmi.server.RemoteStub
    implements java.rmi.Remote
{
    private static final long serialVersionUID = 2;

    // constructors
    public UnderscoreHost_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }

}
