#
# StarshipOS Copyright (c) 2013-2025. R.A. James
#

# 0: symbol
crules.err.var.must.be.final=\
    Static variable {0} must be final
crules.should.not.use.eager.string.evaluation=\
    Should not use eager string evaluation. Use lazy version instead.
crules.should.not.use.lazy.string.evaluation=\
    Should not use eager lazy evaluation. Use eager version instead.
crules.no.defined.by=\
    This method implements a public API method, and should be marked with @DefinedBy.
crules.wrong.defined.by=\
    This method implements a public API method, and is marked with incorrect @DefinedBy.
crules.defined.by.no.api=\
    This method does not implement a public API method, and should not be marked with @DefinedBy.
crules.use.of.legacy.log.method=\
    Should not use legacy Log or JCDiagnostic.Factory methods when methods accepting an Error/Warning/Note/Fragment key can be used.
