/*
 * StarshipOS Copyright (c) 2002-2025. R.A. James
 */

/*
 * @test
 * @bug 4684378
 * @summary generics: verify error in generated bytecode
 * @author gafter
 *
 * @compile  T4684378.java
 * @run main T4684378
 */

import java.util.Stack;
public class T4684378 {
    public static void main(String[] argv) {
        Stack<String> bar = new Stack<String>();
        String foo;

        // Compiles, but causes verify error
        foo=(bar.empty()?"":bar.peek()).intern();

        // The following two work fine
        foo = (bar.empty()?"":bar.peek().intern());
        foo = (bar.empty()?"":(String)bar.peek()).intern();
    }
}
