/*
 * StarshipOS Copyright (c) 2016-2025. R.A. James
 */

/*
 * @test
 * @bug 8166304
 * @summary Skipping access check for classes generated by core reflection
 * @compile fakeMethodAccessor.jasm
 * @run main FakeMethodAcc
 */

/*
 * Test that trying to create a sub-type of a 'magic' jdk.internal.reflect
 * class should fail with an IllegalAccessError exception.
*/
public class FakeMethodAcc {
    public static void main(String args[]) throws Throwable {

        System.out.println("Regression test for bug 8166304");
        try {
            Class newClass = Class.forName("fakeMethodAccessor");
            throw new RuntimeException(
                "Missing expected IllegalAccessError exception");
        } catch (java.lang.IllegalAccessError e) {
        }
    }
}
