/*
 * StarshipOS Copyright (c) 2023-2025. R.A. James
 */
package jdk.internal.event;

/**
 * Event recording error exceptions.
 */
public final class ErrorThrownEvent extends Event {
    public String message;
    public Class<?> thrownClass;

    public static void commit(long start, String message, Class<?> thrownClass) {
        // Generated by JFR
    }

    public static boolean enabled() {
        // Generated by JFR
        return false;
    }

    public static long timestamp() {
        // Generated by JFR
        return 0;
    }
}
