/*
 * StarshipOS Copyright (c) 2023-2025. R.A. James
 */
package jdk.internal.event;

/**
 * Event recording file writes.
 */
public final class FileWriteEvent extends Event {

    // The order of these fields must be the same as the parameters in
    // commit(..., String, long)
    public String path;
    public long bytesWritten;

    public static boolean enabled() {
        // Generated by JFR
        return false;
    }

    public static long timestamp() {
        // Generated by JFR
        return 0L;
    }

    public static boolean shouldCommit(long duration) {
        // Generated by JFR
        return false;
    }

    public static void commit(long start, long duration, String path, long bytesWritten) {
        // Generated by JFR
    }
}
