/*
 * StarshipOS Copyright (c) 2013-2025. R.A. James
 */

/*
 * @test
 * @bug 8008164 8169819 8183037 8182765 8196202 8184205 8242649 8253117
 * @summary Test styles on HTML tables generated by javadoc.
 * @library ../../lib
 * @modules jdk.javadoc/jdk.javadoc.internal.tool
 * @build javadoc.tester.*
 * @run main TestHtmlTableStyles
 */

import javadoc.tester.JavadocTester;

public class TestHtmlTableStyles extends JavadocTester {

    public static void main(String... args) throws Exception {
        var tester = new TestHtmlTableStyles();
        tester.runTests();
    }

    @Test
    public void test() {
        javadoc("-d", "out",
                "-sourcepath", testSrc,
                "-use",
                "pkg1", "pkg2");
        checkExit(Exit.ERROR);
        checkOutput(Output.OUT, true,
                "attribute not supported in HTML5: summary",
                """
                    attribute "border" for table only accepts "" or "1": border""",
                "attribute not supported in HTML5: cellpadding",
                "attribute not supported in HTML5: cellspacing",
                "attribute not supported in HTML5: align");

        checkOutput("pkg1/TestTable.html", true,
                """
                    <table summary="Summary" border cellpadding=3 cellspacing=1>""",
                """
                    <div class="caption"><span>Fields</span></div>
                    <div class="summary-table three-column-summary">""",
                """
                    <div class="caption"><span>Constructors</span></div>
                    <div class="summary-table two-column-summary">""",
                """
                    <div class="summary-table three-column-summary">""");

        checkOutput("pkg1/package-summary.html", true,
                """
                    <div class="caption"><span>Classes</span></div>
                    <div class="summary-table two-column-summary">""");

        checkOutput("pkg1/class-use/TestTable.html", true,
                """
                    <div class="summary-table two-column-summary">""");

        checkOutput("index.html", true,
                """
                    <div id="all-packages-table">
                    <div class="caption"><span>Packages</span></div>
                    <div class="summary-table two-column-summary">""");

        checkOutput("deprecated-list.html", true,
            """
                    <div id="method">
                    <div class="caption"><span>Deprecated Methods</span></div>
                    <div class="summary-table two-column-summary">""");

        checkOutput("constant-values.html", true,
            """
                <div class="summary-table three-column-summary">""");
    }
}
