/*
 * StarshipOS Copyright (c) 2023-2025. R.A. James
 */

/*
 * @test
 * @bug 8311546
 * @summary Adopt de-facto standards on x509 Name Constraints with leading dot. Certs
 * can be generated by running generate-certs.sh
 * @run main LeadingPeriod
 */

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.security.Security;
import java.security.cert.*;

public class LeadingPeriod {

    public static void main(String[] args) throws Exception {
        String certs = System.getProperty("test.src", "./") + "/certs/";
        validate(certs + "withoutLeadingPeriod");
        validate(certs + "withLeadingPeriod");
    }

    public static void validate(String certPath) throws Exception {
        byte[] targetCertBytes = Files.readAllBytes(Paths.get(certPath + "/leaf.pem"));
        byte[] caCertBytes = Files.readAllBytes(Paths.get(certPath + "/ca.pem"));

        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        Certificate caCert = cf.generateCertificate(new ByteArrayInputStream(caCertBytes));
        Certificate targetCert = cf.generateCertificate(new ByteArrayInputStream(targetCertBytes));

        TrustAnchor anchor = new TrustAnchor((X509Certificate) caCert, null);

        PKIXParameters params = new PKIXParameters(Collections.singleton(anchor));

        // Disable certificate revocation checking
        params.setRevocationEnabled(false);

        // Set validity date, so that validation won't fail when cert expires
        params.setDate(((X509Certificate)targetCert).getNotBefore());

        CertPath path = cf.generateCertPath(List.of(targetCert, caCert));

        CertPathValidator validator = CertPathValidator.getInstance("PKIX");
        validator.validate(path, params);
    }
}
