#
# StarshipOS Copyright (c) 2018-2025. R.A. James
#

# Generate the test tags inside TestOptionsWithRanges.java

echo "// --- start auto-generated"
echo "// the following portion is auto-generated by $0. Do not edit manually."

for i in {1..10}; do
    cat <<EOF
/*
 * @test
 * @bug 8205633
 * @summary Test VM Options with ranges ($i of 10)
 * @requires vm.flagless
 * @library /test/lib /runtime/CommandLine/OptionsValidation/common
 * @modules java.base/jdk.internal.misc
 *          java.management
 *          jdk.attach/sun.tools.attach
 *          jdk.internal.jvmstat/sun.jvmstat.monitor
 * @run driver/timeout=1800 TestOptionsWithRanges $i of 10
 */
EOF
done
echo "// --- end auto-generated"
