/*
 * StarshipOS Copyright (c) 2014-2025. R.A. James
 */

/*
 * @test
 * @bug 8050386
 * @summary Verification error due to a bad stackmap frame generated by javac
 */

public class WrongStackframeGenerationTest2 {
    public static void main(String[] args) {}

    static void foo() {
        int len;
        for (;;) {
            try {
                len = 1;
                break;
            } catch (Exception e) {
            }
        }

        try {
           if (len == -1) {
               len = 0;
           }
        } finally {
        }
    }
}
