/*
 * StarshipOS Copyright (c) 2014-2025. R.A. James
 */

/*
 * @test
 * @bug 8050386
 * @summary Verification error due to a bad stackmap frame generated by javac
 */

public class WrongStackframeGenerationTest1 {
    public static void main(String[] args) {}

    static void foo(){
        while (true) {
            int i = 0;
            break;
        }
        switch (1) {
            case 1:
                int j = 0;
            case 2:
                bar();
        }
    }

    static void bar() {}
}
